### PR TITLE
References #20

### PR DESCRIPTION
**Pull request by asm0dey**
Sorry, that's first time when I write C code in my life. Could you please tell me what should I fix? This is just MVP, where thread sleeps for 100ms on each change.

### CODE REVIEW

**Comment by FedeDP** [comment]
Mmmh the problem with this implementation is that it is blocking.
I think we'd better wait for my devel branch to be merged before implementing this, as i'm touching right this part.
Sorry i forgot that!

It is better to make this change myself in my devel branch.
So, i'll close this PR and ask you to be patient for a while :)

In the meantime you can use your locally modified version though!

I'll close the issue as soon as devel branch is merged so you'll get notified.

Thank you very much and sorry again!

**Comment by asm0dey** [comment]
But I think in most cases blocking implementation is ok, because we definitely do not want multiple transitions to run at same time. Or do you think I'm wrong in that?

**Comment by asm0dey** [comment]
Please, execuse me for my insistence, I'm just curious. Of course you're free to close PR if it's irrelevant to your plans on this software.

**Comment by FedeDP** [comment]
Np i'm glad you're looking into this!
The fact is that clight is not multithreaded; it uses blocking io.
Given that only 1 clight instance can be active, i don't see any issue. Obviously a global state boolean variable will be set to lock the transition, but using sleep would completely block clight, delaying all other functions. And what's worst, it would prevent clight to react to external signals (eg SIGTERM).

**Comment by asm0dey** [comment]
Thank you for your answer. I'll wait for you to implement this in correct way :)

**Comment by asm0dey** [comment]
Hi there again!
According to http://man7.org/linux/man-pages/man2/nanosleep.2.html nanosleep allows signals!

**Comment by FedeDP** [comment]
I still prefer to use the already present timerfd interface, just like i do for dimmer :)

**Comment by FedeDP** [comment]
@asm0dey 
Feature request satisfied in https://github.com/FedeDP/Clight/commit/6011a880a4f14aedaf48586ec3c9eb76ea68d3cc.
Please wait for devel branch to be merged into master :)

**Pull request closed without merging**
