### PR TITLE
Switch to using cmake

### PR DESCRIPTION
**Pull request by VorpalBlade**
Again, I can't test sr.ht nor Arch Linux support.

### CODE REVIEW

**Comment by FedeDP** [comment]
Beautiful, thanks!

Btw i was thinking: how much you feel inclined to work on Clight/Clightd?
I mean, you seem pretty eager to help me improve them; I could make you a collaborator, thus giving you write access to repository.
Let me know how you feel about it :)

**Comment by VorpalBlade** [comment]
My main interest is getting it to work (as and when I have time to) on my computer in the way I want it to. I'll probably (try to) look into the multi monitor stuff at least. I don't think I will be much of a maintainer.

**Comment by FedeDP** [comment]
> I don't think I will be much of a maintainer.

I didn't want to make you a maintainer, just a contributor, as it would ease your development (having write access to repository).

**Comment by FedeDP** [comment]
Pull request looks fine!
Just a small request: what about using CMAKE_INSTALL_DATAROOTDIR and CMAKE_INSTALL_SYSCONFDIR here?
```
install(FILES ${EXTRA_DIR}/desktop/clight.desktop
        DESTINATION /etc/xdg/autostart)
install(FILES ${EXTRA_DIR}/desktop/clightc.desktop
        DESTINATION /usr/share/applications)
install(FILES ${EXTRA_DIR}/icons/clight.svg
        DESTINATION /usr/share/icons/hicolor/scalable/apps)
```

**Comment by VorpalBlade** [comment]
As is the case with clightd, this tends to break when using an install prefix other than /usr, but if you have a good idea of how to solve that, tell me. The icon can probably be installed elsewhere, and then the desktop files updated accordingly such that they point to it though.

Using DOCDIR is probably good yes. I have a vague memory from back when I used Arch Linux (10 years ago by now maybe?) that there was some magic post-processing already provided by the PKGBUILD system to move licenses. So it may already be done for you. I may be wrong though.

**Comment by FedeDP** [comment]
> As is the case with clightd, this tends to break when using an install prefix other than /usr, but if you have a good idea of how to solve that, tell me. The icon can probably be installed elsewhere, and then the desktop files updated accordingly such that they point to it though.

Fine for me, thanks!

> Using DOCDIR is probably good yes. I have a vague memory from back when I used Arch Linux (10 years ago by now maybe?) that there was some magic post-processing already provided by the PKGBUILD system to move licenses. So it may already be done for you. I may be wrong though.

Yeah, let's go with DOCDIR on both Clight and Clightd! Then i'll merge both PRs :)

**Pull request merged**
