### PR TITLE
Updated all the C files by wiping out lonely whitespaces.

### PR DESCRIPTION
**Pull request by thecsw**
I just skipped throught the files and made updates to get rid of the whitespaces. You know, all of the coding style rules haha

In no way this is an urgent update, just made it a bit lighter :)

Thanks!

### CODE REVIEW

**Comment by FedeDP** [comment]
This is TOP level priority PR! :)
Thank you very much! Indeed I should use the Kdevelop option to clean whitespaces on file saving, but unfortunately it is quite annoying when dealing with markdown files, thus i leave it off.

Thank you!

**Comment by thecsw** [comment]
Thank you! I love Clight, it lets me go to sleep faster than usual!

**Comment by thecsw** [comment]
I updated the PR a bit, forgot to clean whitespaces at the end of lines!

**Comment by FedeDP** [comment]
Thank you very much for both PR and kind words :)

**Pull request merged**
