### PR TITLE
Add a simple Zsh completion

### PR DESCRIPTION
**Pull request by NICHOLAS85**
Adds basic Zsh completion support.

### CODE REVIEW

**Comment by FedeDP** [comment]
Thank you for this PR!

**Comment by NICHOLAS85** [comment]
It looks like Debian and derivatives use `/usr/share/zsh/vendor-completions` instead of `/usr/share/zsh/site-functions` to install packaged completions (although the latter path exist). The CMakeLists.txt file might need to be altered to account for this.

**Comment by FedeDP** [comment]
Thanks for the information! I will give this a look tomorrow!

**Comment by FedeDP** [comment]
I could not find any way to retrieve zsh completions dir; i guess this will be fine in any case! 
Thank you again!

**Comment by FedeDP** [comment]
Maybe we can do like eg: sway does?
```
option('zsh-completions', type: 'boolean', value: true, description: 'Install zsh shell completions.')
option('bash-completions', type: 'boolean', value: true, description: 'Install bash shell completions.')
```
https://github.com/swaywm/sway/blob/master/meson_options.txt
https://github.com/swaywm/sway/blob/master/meson.build#L233

Ie: adding a -DWITH_BASH_COMPLETIONS -DWITH_ZSH_COMPLETIONS options to cmake to enable installing them.
What do you think? If you are fine with that, would you be so kind to provide a PR? Thank you!

**Comment by FedeDP** [comment]
Not that installing 2 small scripts is such a waste that we should absolutely avoid that...

**Comment by NICHOLAS85** [comment]
Sure, I see no harm in allowing people to skip installing completions, as long as the build documentation is updated accordingly. I'll send a pr with that functionality.

> It looks like Debian and derivatives use `/usr/share/zsh/vendor-completions` instead of `/usr/share/zsh/site-functions` to install packaged completions
What should be done about this? Similar to you, I wasn't able to find a way to retrieve the zsh completions dir. Should we just install to both directories?

**Comment by FedeDP** [comment]
I think we should stay with site-functions/ folder, following what sway does: it is much widely adopted and we can assume it does the right thing there. 
Or maybe we could even add a -DWITH_ZSH_COMPLETION_DIR option instead of -DWITH_ZSH_COMPLETIONS (and same for bash completions), and if any path is set use it, otherwise do not install completion script.
This allows clight to even drop bash-completions package from make deps.
But I am not sure still, I will think about it and let you know! Please tell me if you have any preference too!

If I had to explicitly tell you the best way, it would be to actually push both zsh and bash completions script to their upstream packages.
This would free clight from the deps and allows a more standard installation too.

**Comment by FedeDP** [comment]
> If I had to explicitly tell you the best way, it would be to actually push both zsh and bash completions script to their upstream packages.

Mmmh i see bash-completions does not install external packages completions, thus this way is wrong.

**Comment by NICHOLAS85** [comment]
I've created the `-DWITH_*_COMPLETIONS_DIR` pr at #171, lmk what you think!

**Pull request merged**
